minimal: minimal.cpp minimal.vert minimal.frag
	g++ `pkg-config --cflags glfw3 glew` -o minimal minimal.cpp `pkg-config --static --libs glfw3 glew`

minimal_square: minimal_square.cpp minimal.vert minimal.frag
	g++ `pkg-config --cflags glfw3 glew` -o minimal_square minimal_square.cpp `pkg-config --static --libs glfw3 glew`

minimal44: minimal44.cpp minimal.vert minimal.frag
	g++ `pkg-config --cflags glfw3 glew` -o minimal44 minimal44.cpp `pkg-config --static --libs glfw3 glew`

minimal41: minimal41.cpp minimal.vert minimal.frag
	g++ `pkg-config --cflags glfw3 glew` -o minimal41 minimal41.cpp `pkg-config --static --libs glfw3 glew`

minimal33: minimal33.cpp minimal33.vert minimal33.frag
	g++ `pkg-config --cflags glfw3 glew` -o minimal33 minimal33.cpp `pkg-config --static --libs glfw3 glew`
