obj_import: obj_import.cpp default.vert default.frag
	g++ `pkg-config --cflags glfw3 glew` -o obj_import obj_import.cpp `pkg-config --static --libs glfw3 glew`

obj_import33: obj_import33.cpp default33.vert default33.frag
	g++ `pkg-config --cflags glfw3 glew` -o obj_import33 obj_import33.cpp `pkg-config --static --libs glfw3 glew`
