fps_test: fps_test.cpp simple_texturing.vert simple_texturing.frag
	g++ `pkg-config --cflags glfw3 glew` -o fps_test fps_test.cpp `pkg-config --static --libs glfw3 glew`

simple_texturing: simple_texturing.cpp simple_texturing.vert simple_texturing.frag
	g++ `pkg-config --cflags glfw3 glew` -o simple_texturing simple_texturing.cpp `pkg-config --static --libs glfw3 glew`

simple_texturing33: simple_texturing33.cpp simple_texturing33.vert simple_texturing33.frag
	g++ `pkg-config --cflags glfw3 glew` -o simple_texturing33 simple_texturing33.cpp `pkg-config --static --libs glfw3 glew`
