sphere: sphere.cpp default.vert default.frag
	g++ `pkg-config --cflags glfw3 glew` -o sphere sphere.cpp `pkg-config --static --libs glfw3 glew`

sphere33: sphere33.cpp default33.vert default33.frag
	g++ `pkg-config --cflags glfw3 glew` -o sphere33 sphere33.cpp `pkg-config --static --libs glfw3 glew`

