simple_lighting: simple_lighting.cpp simple_lighting.vert simple_lighting.frag
	g++ `pkg-config --cflags glfw3 glew` -o simple_lighting simple_lighting.cpp `pkg-config --static --libs glfw3 glew`

simple_lighting33: simple_lighting33.cpp simple_lighting33.vert simple_lighting33.frag
	g++ `pkg-config --cflags glfw3 glew` -o simple_lighting33 simple_lighting33.cpp `pkg-config --static --libs glfw3 glew`
